# Generated by Django 4.0.2 on 2022-03-14 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_analyzes_show'),
        ('medicalCard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcard',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patients'),
        ),
    ]
