# Generated by Django 4.0.2 on 2022-03-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCard', '0002_alter_medicalcard_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcard',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
