# Generated by Django 4.0.2 on 2022-02-21 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sex', models.CharField(choices=[('Женский', 'Женский'), ('Мужской', 'Мужской')], max_length=20)),
                ('Name', models.CharField(max_length=100)),
                ('Surname', models.CharField(max_length=100)),
                ('Patronymic', models.CharField(max_length=100)),
                ('Position', models.CharField(max_length=50)),
                ('Date_of_employment', models.DateField(blank=True)),
                ('Inn', models.CharField(blank=True, max_length=50)),
                ('Place_of_residence', models.CharField(blank=True, max_length=100)),
                ('Telephone', models.CharField(max_length=100)),
                ('Certificate', models.CharField(max_length=100)),
                ('photo', models.CharField(blank=True, max_length=30)),
                ('Email', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Specialists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('photo', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('Женский', 'Женский'), ('Мужской', 'Мужской')], max_length=20)),
                ('education', models.CharField(max_length=150)),
                ('passport_num', models.CharField(max_length=20)),
                ('inn', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True)),
                ('specialization', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.specializations')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('edit_tables', 'Может редактировать таблицы'), ('add_lesson', 'Может добавлять занятие'), ('add_workout', 'Может добавлять отработку/отмену'), ('view_schedule', 'Может просматривать расписание')),
            },
        ),
        migrations.CreateModel(
            name='Analyzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Новый', 'Новый'), ('Ожидание', 'Ожидание'), ('Выполнен', 'Выполнен')], max_length=20)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.patients')),
                ('specialist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.specialists')),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.analyzestype')),
            ],
        ),
    ]
