# Generated by Django 4.0.2 on 2022-02-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzestype',
            name='title',
            field=models.CharField(max_length=240),
        ),
    ]
