# Generated by Django 4.0.2 on 2022-03-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_specialistgroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialists',
            name='place_of_residence',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
