# Generated by Django 4.0.2 on 2022-03-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_specialists_place_of_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialists',
            name='place_of_residence',
            field=models.CharField(blank=True, max_length=100, verbose_name='Место проживания'),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='sex',
            field=models.CharField(blank=True, choices=[('Женщина', 'Женщина'), ('Мужчина', 'Мужчина')], max_length=20, verbose_name='Пол'),
        ),
    ]
