# Generated by Django 4.0.2 on 2022-03-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_remove_timetable_specialist'),
        ('user', '0006_alter_specialists_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialists',
            name='timetable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.timetable'),
        ),
    ]
