# Generated by Django 4.0.2 on 2022-03-23 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_specialists_email_alter_specialists_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialists',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.specializations', verbose_name='Специализация'),
        ),
    ]
