# Generated by Django 4.0.2 on 2022-04-09 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_specialists_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialists',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 10, 56, 31, 521823, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
