# Generated by Django 4.0.2 on 2022-04-09 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_specialistsactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialistsactivity',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='specialistsactivity',
            name='start_date',
        ),
        migrations.AddField(
            model_name='specialistsactivity',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialistsactivity',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialistsactivity',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
