# Generated by Django 4.0.2 on 2022-04-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_specialistsactivity_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistsactivity',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
