# Generated by Django 4.0.2 on 2022-04-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_specialistsactivity_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistsactivity',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
