# Generated by Django 4.0.2 on 2022-02-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sex', models.CharField(choices=[('Женский', 'Женский'), ('Мужской', 'Мужской')], max_length=20)),
                ('Name', models.CharField(max_length=100)),
                ('Surname', models.CharField(max_length=100)),
                ('Patronymic', models.CharField(max_length=100)),
                ('Date_of_birth', models.DateField(blank=True)),
                ('Place_of_residence', models.CharField(max_length=100)),
                ('Blood_type', models.CharField(choices=[('I+', 'I+'), ('II+', 'II+'), ('III+', 'III+'), ('IV+', 'IV+'), ('I-', 'I-'), ('II-', 'II-'), ('III-', 'III-'), ('IV-', 'IV-')], max_length=10)),
                ('Telephone', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=30)),
            ],
        ),
    ]
