# Generated by Django 4.0.2 on 2022-02-23 08:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='data_joined',
            field=models.DateField(auto_created=True, blank=True, default=datetime.datetime(2022, 2, 23, 8, 17, 48, 263437, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
    ]
