# Generated by Django 4.0.2 on 2022-02-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='Blood_type',
            field=models.CharField(blank=True, choices=[('I+', 'I+'), ('II+', 'II+'), ('III+', 'III+'), ('IV+', 'IV+'), ('I-', 'I-'), ('II-', 'II-'), ('III-', 'III-'), ('IV-', 'IV-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patients',
            name='Email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='patients',
            name='Place_of_residence',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patients',
            name='Telephone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
