# Generated by Django 4.0.2 on 2022-02-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patients_blood_type_alter_patients_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/patient/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='Sex',
            field=models.CharField(choices=[('Женщина', 'Женщина'), ('Мужчина', 'Мужчина')], max_length=20),
        ),
    ]
