# Generated by Django 4.0.2 on 2022-02-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patients_photo_alter_patients_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, upload_to='photos/patient/%m/%d/'),
        ),
    ]
