# Generated by Django 4.0.2 on 2022-02-21 00:05

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patients_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, storage=django.core.files.storage.FileSystemStorage(location='photos/patient/'), upload_to='photos/patient/%m/%d/'),
        ),
    ]
