# Generated by Django 4.0.2 on 2022-02-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patients_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, upload_to='photos/patient/%m/%d/'),
        ),
    ]
