# Generated by Django 4.0.2 on 2022-03-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_analyzes_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='photo',
            field=models.ImageField(blank=True, default='photos/unnamed.jpg', max_length=210, null=True, upload_to='photos/patient/%m/%d/'),
        ),
    ]
