# Generated by Django 4.0.2 on 2022-03-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_patients_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzes',
            name='date_of_change',
            field=models.DateTimeField(),
        ),
    ]
