# Generated by Django 4.0.2 on 2022-04-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_alter_patients_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyzes',
            old_name='test_date',
            new_name='date',
        ),
    ]
