# Generated by Django 4.0.2 on 2022-04-10 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0016_rename_test_date_analyzes_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='sickList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateIssue', models.DateTimeField(auto_now=True)),
                ('orgn', models.CharField(blank=True, max_length=100)),
                ('disability_code', models.CharField(blank=True, max_length=100)),
                ('disability_code_addit', models.CharField(blank=True, max_length=100)),
                ('place_of_work', models.CharField(blank=True, max_length=100)),
                ('based', models.BooleanField(default=False)),
                ('currently', models.BooleanField(default=False)),
                ('number_work', models.CharField(blank=True, max_length=100)),
                ('public_organizations', models.CharField(blank=True, max_length=100)),
                ('from_what_date', models.DateTimeField(auto_now=True)),
                ('by_what_number', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patients')),
                ('specialist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
