# Generated by Django 4.0.2 on 2022-04-14 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sickList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateIssue', models.DateTimeField(auto_now=True)),
                ('md_organization', models.CharField(blank=True, max_length=100)),
                ('address_of_md_organization', models.CharField(blank=True, max_length=100)),
                ('orgn', models.CharField(blank=True, max_length=100)),
                ('disability_code', models.CharField(blank=True, max_length=100)),
                ('disability_code_addit', models.CharField(max_length=100)),
                ('place_of_work', models.CharField(max_length=100)),
                ('based', models.BooleanField(default=False)),
                ('currently', models.BooleanField(default=False)),
                ('number_work', models.CharField(blank=True, max_length=100)),
                ('public_organizations', models.BooleanField(default=False)),
                ('from_what_date', models.DateTimeField(auto_now=True)),
                ('by_what_number', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patients')),
            ],
        ),
    ]
