# Generated by Django 4.0.2 on 2022-04-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sicklist',
            name='place_of_work',
            field=models.CharField(max_length=100),
        ),
    ]
