# Generated by Django 4.0.2 on 2022-04-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicklist', '0002_alter_sicklist_place_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sicklist',
            name='disability_code_addit',
            field=models.CharField(max_length=100),
        ),
    ]
